const PLUGIN_VIDEOCALL = 'janus.plugin.videocall'

const STREAM_LOCAL                  = 'STREAM_LOCAL'
const STREAM_REMOTE                 = 'STREAM_REMOTE'

const VIDEOCALL_LIST                = 'VIDEOCALL_LIST'
const VIDEOCALL_REGISTERED          = 'VIDEOCALL_REGISTERED'
const VIDEOCALL_CALLING             = 'VIDEOCALL_CALLING'
const VIDEOCALL_USER_CALL_NOT_EXIST = 'VIDEOCALL_USER_CALL_NOT_EXIST'
const VIDEOCALL_INCOMINGCALL        = 'VIDEOCALL_INCOMINGCALL'
const VIDEOCALL_ACCEPTED            = 'VIDEOCALL_ACCEPTED'
const VIDEOCALL_HANGUP              = 'VIDEOCALL_HANGUP'

export const PLUGIN_NAME = {
  PLUGIN_VIDEOCALL: 'janus.plugin.videocall'
}
export const EV_NAME = {
  STREAM_LOCAL,
  STREAM_REMOTE,
  
  VIDEOCALL_LIST,
  VIDEOCALL_REGISTERED,
  VIDEOCALL_CALLING,
  VIDEOCALL_USER_CALL_NOT_EXIST,
  VIDEOCALL_INCOMINGCALL,
  VIDEOCALL_ACCEPTED,
  VIDEOCALL_HANGUP
}

export default {
  PLUGIN_NAME,
  EV_NAME
}